<a href="https://colab.research.google.com/github/grjadhav409/MCF7-inhibitors-prediction-using-ML/blob/main/3_0_discriptors_rdkit.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# deepchem

## lib

In [ ]:
!pip install deepchem
!pip install git+https://github.com/mordred-descriptor/mordred
!pip install rdkit-pypi
!pip install pubchempy


import deepchem as dc
import numpy as np
import pandas as pd

Successfully installed rdkit-pypi-2022.3.1
ERROR: Operation cancelled by user

ModuleNotFoundError: ignored

## data import

In [ ]:
import pandas as pd

In [ ]:
df= pd.read_csv("/content/drive/MyDrive/Colab Notebooks/drug discovery/MCF7/data/2.pIC50_lipinski_mcf7.csv")

In [ ]:
df

,Unnamed: 0,Unnamed: 0.1,molecule_chembl_id,canonical_smiles,class,MW,LogP,NumHDonors,NumHAcceptors,pIC50
0,0,0,CHEMBL1672983,COc1ccc(Cn2c3nc(-c4ccc([N+](=O)[O-])cc4)nc4c(n...,intermediate,549.547,4.17680,0.0,11.0,5.244125
1,1,1,CHEMBL1672986,COc1ccc(Cn2cnc3c4nc(=O)n(Cc5ccc(F)cc5)c-4ncnc3...,intermediate,416.416,2.73210,0.0,8.0,5.397940
2,2,2,CHEMBL2385634,C=CC(=C)CC[C@@H]1[C@@]2(C)CCC[C@](C)(COC(=O)/C...,inactive,482.661,6.45330,2.0,5.0,4.813326
3,3,3,CHEMBL2402999,COc1cc(-c2nc3sc4c(c3c(=O)n2C(Cc2ccccc2)C(=O)O)...,inactive,520.607,4.89800,1.0,8.0,4.299902
4,4,5,CHEMBL1684472,CC[C@@H](C)C[C@@H](C)/C=C/CC[C@@H](O)[C@H](Cc1...,intermediate,333.516,4.29230,3.0,3.0,5.207608
...,...,...,...,...,...,...,...,...,...,...
32297,32297,37501,CHEMBL4786862,CC/C=C/C(=O)Nc1cccc(Oc2nc(Nc3cccc(OC)c3)nc3ccs...,inactive,446.532,6.14050,2.0,7.0,4.362110
32298,32298,37502,CHEMBL4799310,CC(C)/C=C/C(=O)Nc1cccc(Oc2nc(Nc3cccc(C#N)c3)nc...,inactive,455.543,6.24958,2.0,7.0,4.301030
32299,32299,37503,CHEMBL2017434,COc1cc2cc(c1)NC(=O)CCCCCCC=CC[C@H](OC(=O)CNC(=...,inactive,566.783,7.20160,2.0,5.0,4.920819
32300,32300,37505,CHEMBL2153403,O=C1C(=O)N(CCn2cc(Cn3cc(F)c(=O)n(Cc4cn(CCN5C(=...,intermediate,638.576,-0.11230,0.0,14.0,4.000000
32301,32301,37506,CHEMBL2153405,O=C1C(=O)N(CCn2cc(Cn3cc(Cl)c(=O)n(Cc4cn(CCN5C(...,active,655.031,0.40200,0.0,14.0,4.000000

## discriptor calculations

In [ ]:
smiles1 = df['canonical_smiles'].tolist()

In [ ]:
smiles1

In [ ]:

#featurizer = dc.feat.CircularFingerprint(size=1024)
#featurizer = dc.feat.MACCSKeysFingerprint()
#featurizer=dc.feat.ConvMolFeaturizer(per_atom_fragmentation=False)
#featurizer = dc.feat.PubChemFingerprint() #required rdkit and pubchempy installed
featurizer = dc.feat.RDKitDescriptors()
#featurizer = dc.feat.MordredDescriptors(ignore_3D=True)



discriptors = featurizer.featurize(smiles1)

In [ ]:
X_rdkit = pd.DataFrame(data=discriptors)
X_rdkit

,0,1,2,3,4,5,6,7,8,9,...,198,199,200,201,202,203,204,205,206,207
0,13.182830,-0.476693,13.182830,0.055287,0.201967,549.547,526.363,549.176067,204.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,13.199973,-0.440714,13.199973,0.222894,0.437852,416.416,399.280,416.139702,154.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,12.591705,-0.712759,12.591705,0.026745,0.240164,482.661,440.325,482.303224,192.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,14.202941,-1.166637,14.202941,0.131963,0.352801,520.607,492.383,520.166808,192.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,10.427797,-0.376551,10.427797,0.028222,0.529466,333.516,298.236,333.266779,136.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32297,11.970142,-0.183834,11.970142,0.183834,0.316266,446.532,424.356,446.141262,162.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
32298,12.104517,-0.199427,12.104517,0.199427,0.319567,455.543,434.375,455.141596,164.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
32299,12.642889,-0.364167,12.642889,0.018016,0.290333,566.783,516.383,566.371973,226.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
32300,14.696218,-1.170241,14.696218,0.122563,0.187356,638.576,615.392,638.178607,236.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
32301,13.336314,-0.713877,13.336314,0.056006,0.191339,655.031,631.847,654.149056,236.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
y_pic50 = df['pIC50']
y_pic50

0        5.244125
1        5.397940
2        4.813326
3        4.299902
4        5.207608
           ...
32297    4.362110
32298    4.301030
32299    4.920819
32300    4.000000
32301    4.000000
Name: pIC50, Length: 32302, dtype: float64

In [ ]:
y_pic50.to_csv('y_pic50.csv')
!cp y_pic50.csv "/content/drive/MyDrive/Colab Notebooks/drug discovery/MCF7/data"

In [ ]:
# replacing values
df2=df['class'].replace(['active', 'intermediate','inactive'],
                        [1,2,3])
df2

0        2
1        2
2        3
3        3
4        2
        ..
32297    3
32298    3
32299    3
32300    2
32301    1
Name: class, Length: 32302, dtype: int64

In [ ]:
df2.to_csv('y_class.csv')
!cp y_class.csv "/content/drive/MyDrive/Colab Notebooks/drug discovery/MCF7/data"

In [ ]:
# replacing values
df3=df['class'].replace(['active', 'intermediate','inactive'],
                        [1,2,0])




df3

cp: cannot stat 'y_class01.csv': No such file or directory

0        2
1        2
2        0
3        0
4        2
        ..
32297    0
32298    0
32299    0
32300    2
32301    1
Name: class, Length: 32302, dtype: int64

In [ ]:
df3.to_csv('y_class_01.csv')
!cp y_class_01.csv "/content/drive/MyDrive/Colab Notebooks/drug discovery/MCF7/data"

NameError: ignored

## data export

In [ ]:
X_rdkit.to_csv('X_rdkit.csv')
!cp X_rdkit.csv "/content/drive/MyDrive/Colab Notebooks/drug discovery/MCF7/data"